"""add admin_coupon table

Revision ID: e34890f76b18
Revises: b180f4732795
Create Date: 2025-07-23 21:48:36.622387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34890f76b18'
down_revision = 'b180f4732795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_coupon',
    sa.Column('id', sa.Integer(), nullable=False, comment='唯一ID'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='券码'),
    sa.Column('discount', sa.Float(), nullable=True, comment='折扣（如0.8表示8折）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='券码描述'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='生效时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否启用（1=启用，0=禁用）'),
    sa.Column('used', sa.Integer(), nullable=True, comment='是否使用（1=已用，0=未用）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_coupon')
    # ### end Alembic commands ###
